/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/events/{userId}": {
    /** Creates an event on the calendar (SERVICE ACCOUNT ONLY) */
    post: operations["createEvent"];
  };
  "/v1/credentials/link": {
    /**
     * Link IDP user to a calDAV server
     * @description Note: Existing links will be overwritten!<br/>Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    post: operations["linkCaldavToUser"];
  };
  "/v1/calendar/set": {
    /**
     * Sets the user's linked calendar
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    post: operations["setOrUpdateCalendar"];
  };
  "/v1/credentials/status": {
    /**
     * The calDAV link status of the user
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    get: operations["linkStatus"];
  };
  "/v1/calendar/list": {
    /**
     * Gets a list of available calendars
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    get: operations["getListOfCalendars"];
  };
  "/v1/events/{userId}/delete": {
    /**
     * Deletes an event from the calendar (SERVICE ACCOUNT ONLY)
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use) && isServiceAccount(authentication)</strong>
     */
    delete: operations["deleteEvent"];
  };
  "/v1/credentials/unlink": {
    /**
     * Unlink IDP user from a calDAV server credentials
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    delete: operations["unlinkUser"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateEventRequestBody: {
      eventId: string;
      title: string;
      description: string;
      location: string;
      /** Format: date-time */
      startDate: string;
      /** Format: date-time */
      endDate: string;
    };
    ErrorResponse: {
      /** Format: int32 */
      status: number;
      type: string;
      message: string;
      detail: string;
      instance: string;
    };
    CalendarListEntryResponse: {
      name: string;
      href: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Creates an event on the calendar (SERVICE ACCOUNT ONLY) */
  createEvent: {
    parameters: {
      path: {
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEventRequestBody"];
      };
    };
    responses: {
      /** @description Event is created */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Link IDP user to a calDAV server
   * @description Note: Existing links will be overwritten!<br/>Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  linkCaldavToUser: {
    parameters: {
      query: {
        "base-url": string;
        "auth-scope": string;
        "auth-token": string;
      };
    };
    responses: {
      /** @description Link between the calDAV and Idp has been made */
      204: {
        content: {
          "*/*": unknown;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Sets the user's linked calendar
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  setOrUpdateCalendar: {
    parameters: {
      query?: {
        href?: string;
      };
    };
    responses: {
      /** @description Linked calendar has been updated */
      202: {
        content: {
          "*/*": unknown;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * The calDAV link status of the user
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  linkStatus: {
    responses: {
      /** @description Link status */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Gets a list of available calendars
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  getListOfCalendars: {
    responses: {
      /** @description List of calendars */
      200: {
        content: {
          "application/json": components["schemas"]["CalendarListEntryResponse"][];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Deletes an event from the calendar (SERVICE ACCOUNT ONLY)
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use) && isServiceAccount(authentication)</strong>
   */
  deleteEvent: {
    parameters: {
      query: {
        "event-id": string;
      };
      path: {
        userId: string;
      };
    };
    responses: {
      /** @description Event is deleted */
      204: {
        content: {
          "*/*": unknown;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Unlink IDP user from a calDAV server credentials
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  unlinkUser: {
    responses: {
      /** @description Credentials are removed and user is unlinked */
      204: {
        content: {
          "*/*": unknown;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
