/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/token/force-refresh-token": {
    /**
     * Retrieve a fresh access token to interact with the @AH APIs
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    post: operations["forceRefreshAccessToken"];
  };
  "/v1/entra/end": {
    /**
     * Link IDP user to Azure Entra account credentials (access_token, refresh_token)
     * @description Note: Existing links will be overwritten!<br/>Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    post: operations["linkUserWithAzureEntra"];
  };
  "/v1/token/access-token/{userId}": {
    /**
     * Retrieve an access token from a specific user (SERVICE ACCOUNTS ONLY)
     * @description Required scopes expression: <strong>isServiceAccount(authentication) && hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    get: operations["getAccessTokenFromUserId"];
  };
  "/v1/token/access-token/me": {
    /**
     * Retrieve an access token to interact with the @AH APIs
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    get: operations["getAccessToken"];
  };
  "/v1/entra/status": {
    /**
     * The status on the Azure Entra link
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    get: operations["getLinkStatus"];
  };
  "/v1/entra/start": {
    /** Start the Azure Entra authentication flow (returns login-page url) */
    get: operations["getAzureEntraUrl"];
  };
  "/v1/token/revoke-tokens": {
    /**
     * Removes the access token and refresh token from the system and deletes the link with Azure Entra
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    delete: operations["revokeTokens"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      /** Format: int32 */
      status: number;
      type: string;
      message: string;
      detail: string;
      instance: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Retrieve a fresh access token to interact with the @AH APIs
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  forceRefreshAccessToken: {
    responses: {
      /** @description Fresh access token ready to use */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unable to refresh access token due to missing Azure Entra credentials (refresh_token) */
      409: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Link IDP user to Azure Entra account credentials (access_token, refresh_token)
   * @description Note: Existing links will be overwritten!<br/>Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  linkUserWithAzureEntra: {
    parameters: {
      query: {
        code: string;
      };
    };
    responses: {
      /** @description Link between Azure Entra and Idp has been made */
      204: {
        content: {
          "*/*": unknown;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Retrieve an access token from a specific user (SERVICE ACCOUNTS ONLY)
   * @description Required scopes expression: <strong>isServiceAccount(authentication) && hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  getAccessTokenFromUserId: {
    parameters: {
      path: {
        userId: string;
      };
    };
    responses: {
      /** @description (Fresh) usable access token ready to use */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Retrieve an access token to interact with the @AH APIs
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  getAccessToken: {
    responses: {
      /** @description (Fresh) usable access token ready to use */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * The status on the Azure Entra link
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  getLinkStatus: {
    responses: {
      /** @description The status of the Azure Entra link */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Start the Azure Entra authentication flow (returns login-page url) */
  getAzureEntraUrl: {
    responses: {
      /** @description Get the azure entra authentication url */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Removes the access token and refresh token from the system and deletes the link with Azure Entra
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  revokeTokens: {
    responses: {
      /** @description Access and refresh token are removed and user is unlinked */
      204: {
        content: {
          "*/*": unknown;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unable to remove access and refresh token due to missing Azure Entra credentials */
      409: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
