/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/token/force-refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve a fresh access token to interact with the @AH APIs
         * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
         */
        post: operations["forceRefreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entra/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link IDP user to Azure Entra account credentials (access_token, refresh_token)
         * @description Note: Existing links will be overwritten!<br/>Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
         */
        post: operations["linkUserWithAzureEntra"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/token/access-token/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve an access token from a specific user (SERVICE ACCOUNTS ONLY)
         * @description Required scopes expression: <strong>isServiceAccount(authentication) && hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
         */
        get: operations["getAccessTokenFromUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/token/access-token/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve an access token to interact with the @AH APIs
         * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
         */
        get: operations["getAccessToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entra/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The status on the Azure Entra link
         * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
         */
        get: operations["getLinkStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entra/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start the Azure Entra authentication flow (returns login-page url) */
        get: operations["getAzureEntraUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/token/revoke-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Removes the access token and refresh token from the system and deletes the link with Azure Entra
         * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
         */
        delete: operations["revokeTokens"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** Format: int32 */
            status: number;
            type: string;
            message: string;
            detail: string;
            instance: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forceRefreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fresh access token ready to use */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example xxx.yyy.zzz */
                    "text/plain": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 401,
                     *       "type": "UNAUTHORIZED",
                     *       "message": "You have to be logged in to do this.",
                     *       "detail": "No x-authorization header is present.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 405,
                     *       "type": "METHOD_NOT_ALLOWED",
                     *       "message": "Method not allowed.",
                     *       "detail": "Method not allowed.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 406,
                     *       "type": "NOT_ACCEPTABLE",
                     *       "message": "Not acceptable",
                     *       "detail": "Not acceptable",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unable to refresh access token due to missing Azure Entra credentials (refresh_token) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "CONFLICT",
                     *       "status": 409,
                     *       "message": "Conflict",
                     *       "detail": "Conflict",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 429,
                     *       "type": "RATE_LIMIT",
                     *       "message": "Pace your requests. Read the Rate limit guide.",
                     *       "detail": "Rate limit reached for requests",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "type": "SERVER_ERROR",
                     *       "message": "Retry your request after a brief wait and contact us if the issue persists. Check the status page.",
                     *       "detail": "The server had an error while processing your request",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 502,
                     *       "type": "BAD_GATEWAY",
                     *       "message": "Bad gateway.",
                     *       "detail": "Bad gateway.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 503,
                     *       "type": "ENGINE_OVERLOADED",
                     *       "message": "Our servers are experiencing high traffic. Please retry your requests after a brief wait.",
                     *       "detail": "The engine is currently overloaded, please try again later",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    linkUserWithAzureEntra: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link between Azure Entra and Idp has been made */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 401,
                     *       "type": "UNAUTHORIZED",
                     *       "message": "You have to be logged in to do this.",
                     *       "detail": "No x-authorization header is present.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 405,
                     *       "type": "METHOD_NOT_ALLOWED",
                     *       "message": "Method not allowed.",
                     *       "detail": "Method not allowed.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 406,
                     *       "type": "NOT_ACCEPTABLE",
                     *       "message": "Not acceptable",
                     *       "detail": "Not acceptable",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 429,
                     *       "type": "RATE_LIMIT",
                     *       "message": "Pace your requests. Read the Rate limit guide.",
                     *       "detail": "Rate limit reached for requests",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "type": "SERVER_ERROR",
                     *       "message": "Retry your request after a brief wait and contact us if the issue persists. Check the status page.",
                     *       "detail": "The server had an error while processing your request",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 502,
                     *       "type": "BAD_GATEWAY",
                     *       "message": "Bad gateway.",
                     *       "detail": "Bad gateway.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 503,
                     *       "type": "ENGINE_OVERLOADED",
                     *       "message": "Our servers are experiencing high traffic. Please retry your requests after a brief wait.",
                     *       "detail": "The engine is currently overloaded, please try again later",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAccessTokenFromUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description (Fresh) usable access token ready to use */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example xxx.yyy.zzz */
                    "text/plain": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 401,
                     *       "type": "UNAUTHORIZED",
                     *       "message": "You have to be logged in to do this.",
                     *       "detail": "No x-authorization header is present.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 405,
                     *       "type": "METHOD_NOT_ALLOWED",
                     *       "message": "Method not allowed.",
                     *       "detail": "Method not allowed.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 406,
                     *       "type": "NOT_ACCEPTABLE",
                     *       "message": "Not acceptable",
                     *       "detail": "Not acceptable",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 429,
                     *       "type": "RATE_LIMIT",
                     *       "message": "Pace your requests. Read the Rate limit guide.",
                     *       "detail": "Rate limit reached for requests",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "type": "SERVER_ERROR",
                     *       "message": "Retry your request after a brief wait and contact us if the issue persists. Check the status page.",
                     *       "detail": "The server had an error while processing your request",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 502,
                     *       "type": "BAD_GATEWAY",
                     *       "message": "Bad gateway.",
                     *       "detail": "Bad gateway.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 503,
                     *       "type": "ENGINE_OVERLOADED",
                     *       "message": "Our servers are experiencing high traffic. Please retry your requests after a brief wait.",
                     *       "detail": "The engine is currently overloaded, please try again later",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description (Fresh) usable access token ready to use */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example xxx.yyy.zzz */
                    "text/plain": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 401,
                     *       "type": "UNAUTHORIZED",
                     *       "message": "You have to be logged in to do this.",
                     *       "detail": "No x-authorization header is present.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 405,
                     *       "type": "METHOD_NOT_ALLOWED",
                     *       "message": "Method not allowed.",
                     *       "detail": "Method not allowed.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 406,
                     *       "type": "NOT_ACCEPTABLE",
                     *       "message": "Not acceptable",
                     *       "detail": "Not acceptable",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 429,
                     *       "type": "RATE_LIMIT",
                     *       "message": "Pace your requests. Read the Rate limit guide.",
                     *       "detail": "Rate limit reached for requests",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "type": "SERVER_ERROR",
                     *       "message": "Retry your request after a brief wait and contact us if the issue persists. Check the status page.",
                     *       "detail": "The server had an error while processing your request",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 502,
                     *       "type": "BAD_GATEWAY",
                     *       "message": "Bad gateway.",
                     *       "detail": "Bad gateway.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 503,
                     *       "type": "ENGINE_OVERLOADED",
                     *       "message": "Our servers are experiencing high traffic. Please retry your requests after a brief wait.",
                     *       "detail": "The engine is currently overloaded, please try again later",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLinkStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The status of the Azure Entra link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example linked */
                    "text/plain": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 401,
                     *       "type": "UNAUTHORIZED",
                     *       "message": "You have to be logged in to do this.",
                     *       "detail": "No x-authorization header is present.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 405,
                     *       "type": "METHOD_NOT_ALLOWED",
                     *       "message": "Method not allowed.",
                     *       "detail": "Method not allowed.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 406,
                     *       "type": "NOT_ACCEPTABLE",
                     *       "message": "Not acceptable",
                     *       "detail": "Not acceptable",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 429,
                     *       "type": "RATE_LIMIT",
                     *       "message": "Pace your requests. Read the Rate limit guide.",
                     *       "detail": "Rate limit reached for requests",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "type": "SERVER_ERROR",
                     *       "message": "Retry your request after a brief wait and contact us if the issue persists. Check the status page.",
                     *       "detail": "The server had an error while processing your request",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 502,
                     *       "type": "BAD_GATEWAY",
                     *       "message": "Bad gateway.",
                     *       "detail": "Bad gateway.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 503,
                     *       "type": "ENGINE_OVERLOADED",
                     *       "message": "Our servers are experiencing high traffic. Please retry your requests after a brief wait.",
                     *       "detail": "The engine is currently overloaded, please try again later",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAzureEntraUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get the azure entra authentication url */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example https://example.com/ */
                    "text/plain": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 401,
                     *       "type": "UNAUTHORIZED",
                     *       "message": "You have to be logged in to do this.",
                     *       "detail": "No x-authorization header is present.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 405,
                     *       "type": "METHOD_NOT_ALLOWED",
                     *       "message": "Method not allowed.",
                     *       "detail": "Method not allowed.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 406,
                     *       "type": "NOT_ACCEPTABLE",
                     *       "message": "Not acceptable",
                     *       "detail": "Not acceptable",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 429,
                     *       "type": "RATE_LIMIT",
                     *       "message": "Pace your requests. Read the Rate limit guide.",
                     *       "detail": "Rate limit reached for requests",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "type": "SERVER_ERROR",
                     *       "message": "Retry your request after a brief wait and contact us if the issue persists. Check the status page.",
                     *       "detail": "The server had an error while processing your request",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 502,
                     *       "type": "BAD_GATEWAY",
                     *       "message": "Bad gateway.",
                     *       "detail": "Bad gateway.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 503,
                     *       "type": "ENGINE_OVERLOADED",
                     *       "message": "Our servers are experiencing high traffic. Please retry your requests after a brief wait.",
                     *       "detail": "The engine is currently overloaded, please try again later",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revokeTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access and refresh token are removed and user is unlinked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 401,
                     *       "type": "UNAUTHORIZED",
                     *       "message": "You have to be logged in to do this.",
                     *       "detail": "No x-authorization header is present.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 405,
                     *       "type": "METHOD_NOT_ALLOWED",
                     *       "message": "Method not allowed.",
                     *       "detail": "Method not allowed.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Acceptable */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 406,
                     *       "type": "NOT_ACCEPTABLE",
                     *       "message": "Not acceptable",
                     *       "detail": "Not acceptable",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unable to remove access and refresh token due to missing Azure Entra credentials */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "CONFLICT",
                     *       "status": 409,
                     *       "message": "Conflict",
                     *       "detail": "Conflict",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 429,
                     *       "type": "RATE_LIMIT",
                     *       "message": "Pace your requests. Read the Rate limit guide.",
                     *       "detail": "Rate limit reached for requests",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "type": "SERVER_ERROR",
                     *       "message": "Retry your request after a brief wait and contact us if the issue persists. Check the status page.",
                     *       "detail": "The server had an error while processing your request",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 502,
                     *       "type": "BAD_GATEWAY",
                     *       "message": "Bad gateway.",
                     *       "detail": "Bad gateway.",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 503,
                     *       "type": "ENGINE_OVERLOADED",
                     *       "message": "Our servers are experiencing high traffic. Please retry your requests after a brief wait.",
                     *       "detail": "The engine is currently overloaded, please try again later",
                     *       "instance": "/v1/example/endpoint"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
