/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/sync/{userId}": {
    /**
     * Syncs the schedule with our own records (SERVICE ACCOUNT ONLY)
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use) && isServiceAccount(authentication)</strong>
     */
    post: operations["syncSchedule"];
  };
  "/v1/raw-request/raw-schedule": {
    /** Fetch the schedule and get raw data from the @AH API */
    post: operations["getRawSchedule"];
  };
  "/v1/raw-request/formatted-schedule": {
    /** Fetch the schedule and get formatted data (with activities) from the @AH API */
    post: operations["getFormattedSchedule"];
  };
  "/v1/schedule/{userId}": {
    /**
     * Returns the synced schedule (SERVICE ACCOUNT ONLY)
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use) && isServiceAccount(authentication)</strong>
     */
    get: operations["getScheduleFromId"];
  };
  "/v1/schedule/me": {
    /**
     * Returns the synced schedule
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    get: operations["getSchedule"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      /** Format: int32 */
      status: number;
      type: string;
      message: string;
      detail: string;
      instance: string;
    };
    MissingAccessTokenException: {
      detail: string;
      cause?: {
        stackTrace?: {
            classLoaderName?: string;
            moduleName?: string;
            moduleVersion?: string;
            methodName?: string;
            fileName?: string;
            /** Format: int32 */
            lineNumber?: number;
            className?: string;
            nativeMethod?: boolean;
          }[];
        message?: string;
        localizedMessage?: string;
      };
      stackTrace?: {
          classLoaderName?: string;
          moduleName?: string;
          moduleVersion?: string;
          methodName?: string;
          fileName?: string;
          /** Format: int32 */
          lineNumber?: number;
          className?: string;
          nativeMethod?: boolean;
        }[];
      /** @enum {string} */
      status: "100 CONTINUE" | "101 SWITCHING_PROTOCOLS" | "102 PROCESSING" | "103 EARLY_HINTS" | "103 CHECKPOINT" | "200 OK" | "201 CREATED" | "202 ACCEPTED" | "203 NON_AUTHORITATIVE_INFORMATION" | "204 NO_CONTENT" | "205 RESET_CONTENT" | "206 PARTIAL_CONTENT" | "207 MULTI_STATUS" | "208 ALREADY_REPORTED" | "226 IM_USED" | "300 MULTIPLE_CHOICES" | "301 MOVED_PERMANENTLY" | "302 FOUND" | "302 MOVED_TEMPORARILY" | "303 SEE_OTHER" | "304 NOT_MODIFIED" | "305 USE_PROXY" | "307 TEMPORARY_REDIRECT" | "308 PERMANENT_REDIRECT" | "400 BAD_REQUEST" | "401 UNAUTHORIZED" | "402 PAYMENT_REQUIRED" | "403 FORBIDDEN" | "404 NOT_FOUND" | "405 METHOD_NOT_ALLOWED" | "406 NOT_ACCEPTABLE" | "407 PROXY_AUTHENTICATION_REQUIRED" | "408 REQUEST_TIMEOUT" | "409 CONFLICT" | "410 GONE" | "411 LENGTH_REQUIRED" | "412 PRECONDITION_FAILED" | "413 PAYLOAD_TOO_LARGE" | "413 REQUEST_ENTITY_TOO_LARGE" | "414 URI_TOO_LONG" | "414 REQUEST_URI_TOO_LONG" | "415 UNSUPPORTED_MEDIA_TYPE" | "416 REQUESTED_RANGE_NOT_SATISFIABLE" | "417 EXPECTATION_FAILED" | "418 I_AM_A_TEAPOT" | "419 INSUFFICIENT_SPACE_ON_RESOURCE" | "420 METHOD_FAILURE" | "421 DESTINATION_LOCKED" | "422 UNPROCESSABLE_ENTITY" | "423 LOCKED" | "424 FAILED_DEPENDENCY" | "425 TOO_EARLY" | "426 UPGRADE_REQUIRED" | "428 PRECONDITION_REQUIRED" | "429 TOO_MANY_REQUESTS" | "431 REQUEST_HEADER_FIELDS_TOO_LARGE" | "451 UNAVAILABLE_FOR_LEGAL_REASONS" | "500 INTERNAL_SERVER_ERROR" | "501 NOT_IMPLEMENTED" | "502 BAD_GATEWAY" | "503 SERVICE_UNAVAILABLE" | "504 GATEWAY_TIMEOUT" | "505 HTTP_VERSION_NOT_SUPPORTED" | "506 VARIANT_ALSO_NEGOTIATES" | "507 INSUFFICIENT_STORAGE" | "508 LOOP_DETECTED" | "509 BANDWIDTH_LIMIT_EXCEEDED" | "510 NOT_EXTENDED" | "511 NETWORK_AUTHENTICATION_REQUIRED";
      instance: string;
      message?: string;
      suppressed?: {
          stackTrace?: {
              classLoaderName?: string;
              moduleName?: string;
              moduleVersion?: string;
              methodName?: string;
              fileName?: string;
              /** Format: int32 */
              lineNumber?: number;
              className?: string;
              nativeMethod?: boolean;
            }[];
          message?: string;
          localizedMessage?: string;
        }[];
      localizedMessage?: string;
    };
    SyncStatusResponse: {
      shifts: components["schemas"]["SyncStatusResponseEntries"];
    };
    SyncStatusResponseEntries: {
      new: string[];
      update: string[];
      delete: string[];
    };
    GqlScheduleResponseSchedule: {
      startTime: string;
      endTime: string;
      /** Format: int32 */
      minutes: number;
      storeId: string;
      /** Format: int32 */
      leaveMinutes: number;
      /** Format: int32 */
      paidMinutes: number;
      /** Format: int32 */
      sickMinutes: number;
      teamNames: string[];
    };
    ScheduleResponse: {
      shifts: components["schemas"]["ScheduleResponseShiftObject"][];
      /** Format: int32 */
      amount: number;
    };
    ScheduleResponseShiftObject: {
      /** Format: uuid */
      id: string;
      storeId: string;
      /** Format: date-time */
      startDate: string;
      /** Format: date-time */
      endDate: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      departments: ("Management" | "Operatie" | "OperatieGekoeld" | "OperatieKwaliteit" | "Service" | "ServiceIndirect" | "ServiceZelfScan" | "ServiceBalie" | "Vers" | "VersFoodServices" | "Unknown")[];
      activities: Record<string, never>[];
      isFullSickDay: boolean;
      isFullAbsentDay: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Syncs the schedule with our own records (SERVICE ACCOUNT ONLY)
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use) && isServiceAccount(authentication)</strong>
   */
  syncSchedule: {
    parameters: {
      query: {
        /** @description The start date */
        "start-date": string;
        /** @description The end date */
        "end-date": string;
      };
      path: {
        /** @description The id of the user registered at IDP */
        userId: string;
      };
    };
    responses: {
      /** @description Returns the sync results */
      200: {
        content: {
          "*/*": components["schemas"]["SyncStatusResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Missing or invalid Azure Token */
      409: {
        content: {
          "application/problem+json": components["schemas"]["MissingAccessTokenException"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Fetch the schedule and get raw data from the @AH API */
  getRawSchedule: {
    parameters: {
      query: {
        /** @description Azure Entra access token to access the @AH API's (can be retrieved via the 'AppieCal's idp-service') */
        "access-token": string;
        /** @description The start date */
        "start-date": string;
        /** @description The end date */
        "end-date": string;
      };
    };
    responses: {
      /** @description Returns the list of shifts of a user */
      200: {
        content: {
          "*/*": components["schemas"]["GqlScheduleResponseSchedule"][];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Fetch the schedule and get formatted data (with activities) from the @AH API */
  getFormattedSchedule: {
    parameters: {
      query: {
        /** @description Azure Entra access token to access the @AH API's (can be retrieved via the 'AppieCal's idp-service') */
        "access-token": string;
        /** @description The start date */
        "start-date": string;
        /** @description The end date */
        "end-date": string;
      };
    };
    responses: {
      /** @description Returns the list of shifts (formatted with activities) of a user */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Returns the synced schedule (SERVICE ACCOUNT ONLY)
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use) && isServiceAccount(authentication)</strong>
   */
  getScheduleFromId: {
    parameters: {
      query: {
        /** @description The start date */
        "start-date": string;
        /** @description The end date */
        "end-date": string;
      };
      path: {
        /** @description The id of the user registered at IDP */
        userId: string;
      };
    };
    responses: {
      /** @description Returns the list of shifts (formatted with activities) of a user */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Returns the synced schedule
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  getSchedule: {
    parameters: {
      query: {
        /** @description The start date */
        "start-date": string;
        /** @description The end date */
        "end-date": string;
      };
    };
    responses: {
      /** @description Returns the list of shifts (formatted with activities) of a user */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
