/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/sync/automatic/set": {
    /**
     * Turn the automatic sync on or off
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    post: operations["setAutomaticSync"];
  };
  "/v1/sync/manual": {
    /**
     * Sync the users calendar manually
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    get: operations["manualSync"];
  };
  "/v1/sync/automatic/{userId}": {
    /**
     * Sync the users calendar as SERVICE ACCOUNT
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use) && isServiceAccount(authentication)</strong>
     */
    get: operations["automaticSync"];
  };
  "/v1/sync/automatic/status": {
    /**
     * Turn the automatic sync on or off
     * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
     */
    get: operations["getAutomaticSyncStatus"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      /** Format: int32 */
      status: number;
      type: string;
      message: string;
      detail: string;
      instance: string;
    };
    SyncStatusResponse: {
      shifts: components["schemas"]["SyncStatusResponseEntries"];
    };
    SyncStatusResponseEntries: {
      new: string[];
      update: string[];
      delete: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Turn the automatic sync on or off
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  setAutomaticSync: {
    parameters: {
      query: {
        state: boolean;
      };
    };
    responses: {
      /** @description Change successful */
      204: {
        content: never;
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Sync the users calendar manually
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  manualSync: {
    parameters: {
      query: {
        startDate: string;
        endDate: string;
      };
    };
    responses: {
      /** @description Returns the sync results */
      200: {
        content: {
          "*/*": components["schemas"]["SyncStatusResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Sync the users calendar as SERVICE ACCOUNT
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use) && isServiceAccount(authentication)</strong>
   */
  automaticSync: {
    parameters: {
      query: {
        startDate: string;
        endDate: string;
      };
      path: {
        userId: string;
      };
    };
    responses: {
      /** @description Returns the sync results */
      200: {
        content: {
          "*/*": components["schemas"]["SyncStatusResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Turn the automatic sync on or off
   * @description Required scopes expression: <strong>hasScope(https://klrnbk.nl/projects/appiecal:use)</strong>
   */
  getAutomaticSyncStatus: {
    responses: {
      /** @description The status of automatic sync */
      200: {
        content: {
          "*/*": boolean;
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Method Not Allowed */
      405: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Acceptable */
      406: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Bad Gateway */
      502: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/problem+json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
