packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@apollo/protobufjs': set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

patchedDependencies:
  graphql-modules@3.1.1: patches/graphql-modules@3.1.1.patch
